# Generated by Django 4.2.6 on 2023-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0003_chatsession_extracted_symptoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="just_diagnosed",
            field=models.BooleanField(default=False),
        ),
    ]
