# Generated by Django 4.2.6 on 2023-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="conversation_state",
            field=models.CharField(default="GreetingState", max_length=100),
        ),
    ]
