# Generated by Django 4.2.6 on 2023-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnosis", "0005_remove_chatsession_just_diagnosed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="conversation_state",
            field=models.CharField(default="AskSymptomsState", max_length=100),
        ),
    ]
