# Generated by Django 4.2.6 on 2023-10-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0007_users_remove_chatsession_username_chatsession_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='exec_lvl',
            field=models.PositiveIntegerField(default=3, verbose_name='exercise level'),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight_goal',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='UserNotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on', models.BooleanField(default=False)),
                ('latest_meal_plan', models.JSONField(null=True)),
                ('chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('days_notified', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnosis.users')),
            ],
        ),
    ]
